// Generated by scripts/update_git_info.ps1 - do not edit by hand

class GitInfo {
  static const String commitHash = 'e0b5cde38c7eee99744a66b228baf4e6a1e15a21';
  static const String shortHash = 'e0b5cde';
  static const String commitMessage = "chore: update generated git info";
  static const String branch = 'main';
  static const String repositoryUrl = 'https://github.com/gujustud/cribhub_v2';

  static String get commitUrl => '$repositoryUrl/commit/$commitHash';
  static String get repoUrl => repositoryUrl;
}