// Generated by scripts/update_git_info.ps1 - do not edit by hand

class GitInfo {
  static const String commitHash = 'f7237debdd39d5a48e6ff54e9ceceeaed6a62037';
  static const String shortHash = 'f7237de';
  static const String commitMessage = "Disable icon tree-shaking for Flutter web builds.";
  static const String branch = 'main';
  static const String repositoryUrl = 'https://github.com/gujustud/cribhub_v2';

  static String get commitUrl => '$repositoryUrl/commit/$commitHash';
  static String get repoUrl => repositoryUrl;
}