// Generated by scripts/update_git_info.ps1 - do not edit by hand

class GitInfo {
  static const String commitHash = 'c11893df614e284e8e3da96dec58f0f4ac5b2d0c';
  static const String shortHash = 'c11893d';
  static const String commitMessage = "feat: link brands to suppliers and polish purchases";
  static const String branch = 'main';
  static const String repositoryUrl = 'https://github.com/gujustud/cribhub_v2';

  static String get commitUrl => '$repositoryUrl/commit/$commitHash';
  static String get repoUrl => repositoryUrl;
}