# Regenerate lib/git_info.dart from current git. Run from repo root (c:\cribhub).
$ErrorActionPreference = 'Stop'
$repoRoot = if ($PSScriptRoot) { Split-Path -Parent $PSScriptRoot } else { Get-Location }
if (-not (Test-Path (Join-Path $repoRoot '.git'))) { $repoRoot = Get-Location }
Set-Location $repoRoot

$commitHash = (git rev-parse HEAD).Trim()
$shortHash  = (git rev-parse --short=7 HEAD).Trim()
$branch     = (git rev-parse --abbrev-ref HEAD).Trim()
$msg        = (git log -1 --format='%s').Trim()
$msgEscaped = $msg -replace '\\', '\\\\' -replace '"', '\"'

$content = @"
// Generated by scripts/update_git_info.ps1 - do not edit by hand

class GitInfo {
  static const String commitHash = '$commitHash';
  static const String shortHash = '$shortHash';
  static const String commitMessage = "$msgEscaped";
  static const String branch = '$branch';
  static const String repositoryUrl = 'https://github.com/gujustud/cribhub_v2';

  static String get commitUrl => '`$repositoryUrl/commit/`$commitHash';
  static String get repoUrl => repositoryUrl;
}
"@

$outPath = Join-Path $repoRoot 'lib\git_info.dart'
$content | Set-Content -Path $outPath -Encoding UTF8 -NoNewline
Write-Host "Updated $outPath -> $shortHash"
